services:

  web:
    build: .
    command: sh ./run.sh
    volumes:
      - .:/dogapi
    ports:
      - 8000:8000 # HTTP port
      - 5432:5432 # DB port
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dogapi_db
      - POSTGRES_USER=tchramosta
      - POSTGRES_PASSWORD=changeLater