FROM python:3.8

WORKDIR /DogBreedAPI

# copy requirements file into dogapp directory
COPY requirements.txt /DogBreedAPI/


RUN pip install -r requirements.txt

# copy project files into container app directory
COPY ./webservices/ /DogBreedAPI/

CMD ["python", "manage.py", "runserver"]