FROM python:3.8

WORKDIR /dogapp

# copy requirements file into dogapp directory
COPY requirements.txt /dogapp/


RUN pip install -r requirements.txt

# copy project files into container app directory
COPY ./webservices/ /dogapp/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]