# Generated by Django 5.1.1 on 2024-11-12 01:06

import django.db.models.deletion
import dogapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=100)),
                ('friendliness', models.IntegerField(choices=dogapi.models.get_scale)),
                ('trainability', models.IntegerField(choices=dogapi.models.get_scale)),
                ('sheedingamount', models.IntegerField(choices=dogapi.models.get_scale)),
                ('exerciseneeds', models.IntegerField(choices=dogapi.models.get_scale)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('favoritefood', models.CharField(max_length=100)),
                ('favoritetoy', models.CharField(max_length=100)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dogapi.breed')),
            ],
        ),
    ]
